id = "perplexity"
name = "Perplexity"
version = "0.1.0"
description = "Ask questions to Perplexity AI directly from CodeOrbit"
authors = ["CodeOrbit Industries <support@CodeOrbit.dev>"]
repository = "https://github.com/CodeOrbit-industries/CodeOrbit"
schema_version = 1

[slash_commands.perplexity]
description = "Ask a question to Perplexity AI"
requires_argument = true
tooltip_text = "Ask Perplexity"
