name: Bug Report (AI Related)
description: CodeOrbit Agent Panel Bugs
type: "Bug"
labels: ["ai"]
title: "AI: <a short description of the AI Related bug>"
body:
  - type: textarea
    attributes:
      label: Summary
      description: Describe the bug with a one line summary, and provide detailed reproduction steps
      value: |
        <!-- Please insert a one line summary of the issue below -->
        SUMMARY_SENTENCE_HERE

        ### Description
        <!--  Describe with sufficient detail to reproduce from a clean CodeOrbit install. -->
        Steps to trigger the problem:
        1.
        2.
        3.

        Actual Behavior:
        Expected Behavior:

        ### Model Provider Details
        - Provider: (Anthropic via ZedPro, Anthropic via API key, Copilot Chat, Mistral, OpenAI, etc)
        - Model Name:
        - Mode: (Agent Panel, Inline Assistant, Terminal Assistant or Text Threads)
        - MCP Servers in-use:
        - Other Details:
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: CodeOrbit Version and System Specs
      description: 'Open CodeOrbit, and in the command palette select "CodeOrbit: copy system specs into clipboard"'
      placeholder: |
        Output of "CodeOrbit: copy system specs into clipboard"
    validations:
      required: true
