name: Bug Report (Other)
description: |
  Something else is broken in CodeOrbit (exclude crashing).
type: "Bug"
body:
  - type: textarea
    attributes:
      label: Summary
      description: Provide a one sentence summary and detailed reproduction steps
      value: |
        <!-- Begin your issue with a one sentence summary -->
        SUMMARY_SENTENCE_HERE

        ### Description
        <!--  Describe with sufficient detail to reproduce from a clean CodeOrbit install.
          - Any code must be sufficient to reproduce (include context!)
          - Code must as text, not just as a screenshot.
          - Issues with insufficient detail may be summarily closed.
        -->

        DESCRIPTION_HERE

        Steps to reproduce:
        1.
        2.
        3.
        4.

        **Expected Behavior**:
        **Actual Behavior**:

        <!-- Before Submitting, did you:
          1. Include settings.json, keymap.json, .editorconfig if relevant?
          2. Check your CodeOrbit.log for relevant errors? (please include!)
          3. Click Preview to ensure everything looks right?
          4. Hide videos, large images and logs in ``` inside collapsible blocks:

        <details><summary>click to expand</summary>

        ```json

        ```
        </details>
        -->

    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: CodeOrbit Version and System Specs
      description: |
        Open CodeOrbit, from the command palette select "codeorbit: copy system specs into clipboard"
      placeholder: |
        Output of "codeorbit: copy system specs into clipboard"
    validations:
      required: true
