name: Other [Staff Only]
description: CodeOrbit Staff Only
body:
  - type: textarea
    attributes:
      label: Summary
      value: |
        <!-- Please insert a one line summary of the issue below -->
        SUMMARY_SENTENCE_HERE

        ### Description

        IF YOU DO NOT WORK FOR CODEORBIT DO NOT CREATE ISSUES WITH THIS TEMPLATE.
        THEY WILL BE AUTO-CLOSED AND MAY RESULT IN YOU BEING BANNED FROM THE CODEORBIT ISSUE TRACKER.

        FEATURE REQUESTS / SUPPORT REQUESTS SHOULD BE OPENED AS DISCUSSIONS:
          https://github.com/codeorbit-industries/codeorbit/discussions/new/choose
    validations:
      required: true
