id = "toml"
name = "TOML"
description = "TOML support."
version = "0.1.4"
schema_version = 1
authors = [
    "Max Brunsfeld <max@CodeOrbit.dev>",
    "Ammar Arif <evergreenkary@gmail.com>"
]
repository = "https://github.com/CodeOrbit-industries/CodeOrbit"

[language_servers.taplo]
name = "Taplo"
language = "TOML"

[grammars.toml]
repository = "https://github.com/tree-sitter/tree-sitter-toml"
commit = "342d9be207c2dba869b9967124c679b5e6fd0ebe"
