[package]
name = "codeorbit_html"
version = "0.2.1"
edition.workspace = true
publish.workspace = true
license = "Apache-2.0"

[lints]
workspace = true

[lib]
path = "src/html.rs"
crate-type = ["cdylib"]

[dependencies]
codeorbit_extension_api = "0.1.0"
