[package]
name = "codeorbit"
version = "0.1.0"
description = "AI-Powered Development Assistant for Zed"
authors = ["CodeOrbit Team"]
repository = "https://github.com/your-org/codeorbit"
license = "MIT OR Apache-2.0"

[dependencies]
# List any external dependencies your extension requires

[features]
# Define any optional features here

auto_activate = true

[configuration]
# Define your extension's configuration schema here
[configuration.settings]
# Example configuration
# api_key = { type = "string", default = "", description = "API key for CodeOrbit service" }
# model = { type = "string", default = "gpt-4", description = "Default AI model to use" }
