[book]
authors = ["The Zed Team"]
language = "en"
multilingual = false
src = "src"
title = "Zed"
site-url = "/docs/"

[output.html]
no-section-label = true
preferred-dark-theme = "dark"
additional-css = ["theme/page-toc.css", "theme/plugins.css", "theme/highlight.css"]
additional-js  = ["theme/page-toc.js", "theme/plugins.js"]

[output.html.print]
enable = false

# Redirects for `/docs` pages.
#
# All of the source URLs are interpreted relative to mdBook, so they must:
# 1. Not start with `/docs`
# 2. End in `.html`
#
# The destination URLs are interpreted relative to `https://zed.dev`.
# - Redirects to other docs pages should end in `.html`
# - You can link to pages on the Zed site by omitting the `/docs` in front of it.
[output.html.redirect]
# AI
"/docs/ai/agent-panel.html",
"/docs/ai/overview.html",
"/docs/ai/text-threads.html",
"/docs/ai/mcp.html",
"/docs/ai/inline-assistant.html",
"/docs/ai/rules.html",
"/docs/ai/ai-improvement.html",
"/community-links",
"/docs/debugger.html",
"/docs/extensions/mcp-extensions.html",
"/docs/extensions/languages.html",
"/docs/languages/elixir.html",
"/docs/languages/javascript.html",
"/docs/languages/html.html",
"/docs/languages/javascript.html",
"/docs/languages/makefile.html",
"/docs/languages/nim.html",
"/docs/languages/ruby.html",
"/docs/languages/scala.html",
"/docs/languages/python.html",
"/docs/languages/ruby.html",
"/docs/development.html#contributor-links",
"/docs/development.html",
"/docs/development/linux.html",
"/docs/development/macos.html",
"/docs/development/windows.html"

# Our custom preprocessor for expanding commands like `{#kb action::ActionName}`,
# and other docs-related functions.
#
# Comment the below section out if you need to bypass the preprocessor for some reason.
[preprocessor.zed_docs_preprocessor]
command = "cargo run -p docs_preprocessor --"
renderer = ["html"]
