name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
    - name: Cache cargo
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Run tests
      run: |
        cargo test --workspace --no-fail-fast
        cargo clippy --all-targets -- -D warnings
        cargo fmt --all -- --check

  release:
    needs: test
    if: github.event_name == 'release' && github.event.action == 'created'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
    - name: Build release
      run: |
        cargo build --release
        mkdir -p release
        cp target/release/codeorbit release/
        cp -r assets release/
        cp README.md release/
    - name: Create release asset
      uses: softprops/action-gh-release@v1
      with:
        files: release/**/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
